name: Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "laravel/**" # this workflow will only run when changes are made to the laravel directory

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4

      - name: Deploy backend
        run: ssh ec2-user@35.155.24.157 'cd /laravel && git pull origin main && php artisan migrate'

# this command changes the directory to /laravel, pulls the latest changes from the main branch of the remote Git repository, 
# and then executes any pending database migrations in the Laravel application. to update the application codebase and apply any necessary database schema changes.
# git pull origin main: Pulls the latest changes from the remote repository named origin into the local repository's main branch.
# php artisan migrate: Executes the Laravel Artisan command migrate. This command runs any outstanding database migrations defined in your Laravel application.
# Database migrations are used to modify the structure of the database schema, such as creating or altering database tables.

