name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**" # Assuming frontend files are under a 'frontend' directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v2

      - name: Build frontend
        run: docker build -t frontend .

      - name: Deploy frontend
        run: ssh ec2-user@35.254.165.25 'docker pull frontend && docker run -d --name frontend-container -p 80:80 frontend:latest'
